app:
  name: "chat-app"
  env: "docker"

database:
  host: localhost
  port: 5432
  user: chat-user
  password: chat-password
  name: chat
  sslmode: disable

redis:
  host: redis
  port: 6379

jwt:
  secret: "super-secret-local-chat"

services:
  chat:
    host: chat-service
    port: 50051

gateway:
  port: 8080
