services:
  kafka:
    image: apache/kafka:3.8.0
    container_name: demo-kafka
    environment:
      # --- KRaft Mode Configuration ---
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka:9093'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      # The Cluster ID is required to format the storage on startup
      KAFKA_CLUSTER_ID: 'MkU3OEVBNTcwNTJENDM2Qk'
      
      # --- Listeners ---
      # 9092 for clients, 9093 for internal KRaft controller traffic
      KAFKA_LISTENERS: 'PLAINTEXT://:9092,CONTROLLER://:9093'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://localhost:9092'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'PLAINTEXT'
      
      # --- Extra Settings ---
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
      KAFKA_LOG_DIRS: '/var/lib/kafka/data'
    ports:
      - "9092:9092"
      - "9093:9093"
    networks:
      - exam-network
    volumes:
      - kafka-data:/var/lib/kafka/data
    restart: unless-stopped


networks:
  exam-network:
    driver: bridge

volumes:
  kafka-data: